### ISSUE TITLE
Error: Timezone 'Europe/Copenhagen' is either incorrect, or not loaded in the timezone registry.

### ISSUE THREAD

**Issue by rkostov** [mde/timezone-js#169]
This is the code:
timezoneJS.timezone.zoneFileBasePath = '/path/to/library/tz';
timezoneJS.timezone.defaultZoneFile = ['europe', 'asia', 'backward', 'northamerica'];
timezoneJS.timezone.loadingScheme = timezoneJS.timezone.loadingSchemes.MANUAL_LOAD;
timezoneJS.timezone.init({async: false});
dt = new timezoneJS.Date("2015/03/21 01:00:00 +0000", "Asia/Kolkata");
dt.setTimezone("Europe/Copenhagen");
console.log(dt.getTime() / 1000);

**Comment by mde** [comment]
This library is no longer maintained, and this repo is here only for historical interest.
