### ISSUE TITLE
Timezone incorrect or not loaded in the timezone registry

### ISSUE THREAD

**Issue by MasterFO** [mde/timezone-js#171]
Hi,
I've got a problem with this library.

timezoneJS.timezone.zoneFileBasePath = '/js/timezone-js/tz/';
                        timezoneJS.timezone.defaultZoneFile = ['europe', 'asia', 'backward', 'northamerica'];
                        timezoneJS.timezone.loadingSchemes.PRELOAD_ALL;
                        timezoneJS.timezone.init({async: false});
                        dt = new timezoneJS.Date("2015/03/21 01:00:00 +0000", "Europe/London");

Console error:
Uncaught Error: Timezone 'Europe/London' is either incorrect, or not loaded in the timezone registry.

The zoneFileBasePath is correct.
Same error with empty init.
What I have to do?

**Comment by mde** [comment]
This library is no longer maintained, and this repo is here only for historical interest.
