### ISSUE TITLE
incorrect timezone abbreviations

### ISSUE THREAD

**Issue by will87** [mde/timezone-js#173]
Hi,
I've noticed that for some timezones eg. Africa/Tunis and Indian/Mauritius,  the abbreviations retrieved with getTimezoneAbbreviation aren't correct, there seems to be a function (getAbbreviation) in date.js that adds an 'S' to the abbreviation from the Olson files so CET becomes CEST and MUT becomes MUST, making these abbreviations incorrect for these timezones, what is the reason for this?

**Comment by mde** [comment]
Ugh, this is probably something very stupid like looking for a "D" as in 'daylight,' and inserting "S" if it doesn't find it.

**Comment by mde** [comment]
This library is no longer maintained, and this repo is here only for historical interest.
