### ISSUE TITLE
tzdata now available as NPM modules

### ISSUE THREAD

**Issue by rogierschouten** [mde/timezone-js#179]
I've made the olsen timezone data available as a collection of NPM packages. These are preparsed JSON objects in the form that timezone-js needs. 

There is one [tzdata](https://www.npmjs.com/package/tzdata) package that contains all zones, and then there are packages that contain subsets of the time zones:

- tzdata
- tzdata-africa
- tzdata-antarctica
- tzdata-asia
- tzdata-australasia
- tzdata-backward
- tzdata-etcetera
- tzdata-europe
- tzdata-northamerica
- tzdata-pacificnew
- tzdata-southamerica
- tzdata-systemv
- tzdata-backward-utc

The advantage of these packages is that you don't need to download new TZ databases anymore, just running NPM update is enough.

Perhaps you could mention the use of these packages in your README.md?

**Comment by mde** [comment]
Would definitely merge a PR that updates the README with this info!

**Comment by rogierschouten** [comment]
PR #180

**Comment by mde** [comment]
Updates merged, thanks!
