### ISSUE TITLE
invalid date

### ISSUE THREAD

**Issue by DmitrijV1013** [mde/timezone-js#181]
Hi.
We use date.js to display the date.
Use the date display in Spanish.
The problem arises only from the date of the display with the month of January
January Spanish - Enero
 we have var : "Ene 02, 2017"
In date.js : 
.replace(/E+/g, function (token) { return DAYS[_this.getDay()].substring(0, token.length); })
this metod replace and run incorrect action
how to solve this problem?

**Comment by mde** [comment]
All work on this library should probably be stopped in favor of eventually just using the upcoming native `temporal` module: https://github.com/maggiepint/proposal-temporal
