### ISSUE TITLE
Wrong date conversion for certain years in daylight saving time

### ISSUE THREAD

**Issue by madmax25** [mde/timezone-js#187]
Year 1967, 1946, 1945, 1944, 1920 are failing to produce the proper date using timezoneJS 0.4.11 and the latest IANA.org Time Zone Database files from 2018g (Released 2018-10-26).

Please see following failed spec tests:

```
describe('during daylight saving time', function () {
    it('year 1967', function () {
        expect(new timezoneJS.Date(new Date('06/10/1967').getTime(), 'America/Chicago').toString('MM/dd/yyyy')).toBe('06/10/1967');
    });
    it('year 1946', function () {
        expect(new timezoneJS.Date(new Date('06/10/1946').getTime(), 'America/Chicago').toString('MM/dd/yyyy')).toBe('06/10/1946');
    });
    it('year 1945', function () {
        expect(new timezoneJS.Date(new Date('06/10/1945').getTime(), 'America/Chicago').toString('MM/dd/yyyy')).toBe('06/10/1945');
    });
    it('year 1944', function () {
        expect(new timezoneJS.Date(new Date('06/10/1944').getTime(), 'America/Chicago').toString('MM/dd/yyyy')).toBe('06/10/1944');
    });
    it('year 1920', function () {
        expect(new timezoneJS.Date(new Date('06/10/1920').getTime(), 'America/Chicago').toString('MM/dd/yyyy')).toBe('06/10/1920');
    });
});
```

Expected '06/09/1967' to be '06/10/1967'. test/javascript/common/js/lib/TestSpec.js:5:121
Expected '06/09/1946' to be '06/10/1946'. test/javascript/common/js/lib/TestSpec.js:8:121
Expected '06/09/1945' to be '06/10/1945'. test/javascript/common/js/lib/TestSpec.js:11:121
Expected '06/09/1944' to be '06/10/1944'. test/javascript/common/js/lib/TestSpec.js:14:121
Expected '06/09/1920' to be '06/10/1920'. test/javascript/common/js/lib/TestSpec.js:20:121

**Comment by mde** [comment]
This library is no longer maintained.
