### ISSUE TITLE
Using built-in Date in local time zone as a backend of timezone-js is a fundamental mistake

### ISSUE THREAD

**Issue by haozhun** [mde/timezone-js#51]
Suppose my system timezone is Pacific Time. See this example:

```
> new Date(2012,2,11,1,59,0);
Sun Mar 11 2012 01:59:00 GMT-0800 (PST)
> new Date(2012,2,11,2,0,0);
Sun Mar 11 2012 01:00:00 GMT-0800 (PST)
> new Date(2012,2,11,3,0,0);
Sun Mar 11 2012 03:00:00 GMT-0700 (PDT)
```

When using the local timezone, there exists date that simply doesn't exist. Therefore, you shouldn't use the built-in Date in the local timezone as the internal representation of the timezoneJS.Date. However, you are doing this all over your code.

A solution to this issue is to use the UTC time of the built-in Date to represent the timezoneJS.Date, which is guaranteed to work, as long as we don't take Gregorian cut-off time into consideration.

I appreciate your work. This indeed is something useful if correct. And it's great that you're willing to help the community and make it available to everyone. However, This issue and issue #36, are both critical enough that warrants immediate fix. Given issue #36 has been outstanding for quite some time, you probably won't have time to fix both bugs any time soon. Currently, when searching for time zone conversion in js on Google, several top results are directing users to try your code here. Therefore, I believe you should put a noticeable warning on this project's main readme to advise any serious user that wants accurate time conversion to avoid using this code and find alternatives.

**Comment by slominskir** [comment]
Wow.... I guess the fix is to use moment.js instead

**Comment by jboolean** [comment]
My solution was to write my own timezone conversion utility. Not easy, but a lot smaller than momentjs and tailored to my purposes. Unfortunately not open source.
