### ISSUE TITLE
HTTP Error 404.3 - Trying to load TZ file

### ISSUE THREAD

**Issue by thomasenns** [mde/timezone-js#90]
I get the error...

HTTP Error 404.3 - Not Found
The page you are requesting cannot be served because of the extension configuration. If the page is a script, add a handler. If the file should be downloaded, add a MIME map.

When I 'm trying to load the TZ file.  Have a missed a step?

**Comment by nazihnemri** [comment]
Hello , 

@longlho  please can you tell how I can fix this error on windows server iis 2012

**Comment by longlho** [comment]
My bet is something to do with your file serving config for windows server.
Unfortunately I haven't used it enough to know.

**Comment by nazihnemri** [comment]
thanks but I'm new with windows server and i do not now how to add this config so it can load the file
